// Sentence drill prompts — Mexican Spanish as default
// Argentine variant included on prompts where it diverges meaningfully (for BA prep mode later)

export type Category = "family" | "work" | "ba_travel" | "daily" | "dealmaking";
export type Difficulty = 1 | 2 | 3;

export interface Prompt {
  id: string;
  english: string;
  spanish: string; // Mexican Spanish default
  alternates?: string[]; // also-acceptable
  category: Category;
  difficulty: Difficulty;
  notes?: string;
  argentine?: string; // shown when BA mode active
}

export const PROMPTS: Prompt[] = [
  // ---------- FAMILY ----------
  {
    id: "f1",
    english: "Put your shoes on.",
    spanish: "Ponte los zapatos.",
    argentine: "Ponete los zapatos.",
    category: "family",
    difficulty: 1,
    notes: "Imperative + reflexive. Mexico: ponte (tú). Argentina: ponete (vos).",
  },
  {
    id: "f2",
    english: "What's for dinner?",
    spanish: "¿Qué hay de cenar?",
    alternates: ["¿Qué hay para cenar?", "¿Qué vamos a cenar?"],
    category: "family",
    difficulty: 1,
  },
  {
    id: "f3",
    english: "My daughter is learning Spanish at home.",
    spanish: "Mi hija está aprendiendo español en casa.",
    category: "family",
    difficulty: 2,
  },
  {
    id: "f4",
    english: "Did you brush your teeth?",
    spanish: "¿Te lavaste los dientes?",
    alternates: ["¿Te cepillaste los dientes?"],
    category: "family",
    difficulty: 2,
    notes: "In Mexico, 'lavarse los dientes' is more common than 'cepillarse.'",
  },
  {
    id: "f5",
    english: "I'll pick her up after work.",
    spanish: "La recojo después del trabajo.",
    alternates: ["La voy a recoger después del trabajo."],
    category: "family",
    difficulty: 2,
  },
  {
    id: "f6",
    english: "Tell me what happened at school today.",
    spanish: "Cuéntame qué pasó en la escuela hoy.",
    argentine: "Contame qué pasó en la escuela hoy.",
    category: "family",
    difficulty: 2,
  },
  {
    id: "f7",
    english: "I'm proud of you.",
    spanish: "Estoy orgulloso de ti.",
    argentine: "Estoy orgulloso de vos.",
    category: "family",
    difficulty: 1,
    notes: "Use 'orgullosa' if speaker is female. 'De ti' in Mexico, 'de vos' in Argentina.",
  },
  {
    id: "f8",
    english: "Don't forget your backpack.",
    spanish: "No olvides tu mochila.",
    alternates: ["No te olvides la mochila."],
    category: "family",
    difficulty: 2,
  },
  {
    id: "f9",
    english: "Are you hungry?",
    spanish: "¿Tienes hambre?",
    argentine: "¿Tenés hambre?",
    category: "family",
    difficulty: 1,
  },
  {
    id: "f10",
    english: "I love you.",
    spanish: "Te quiero.",
    alternates: ["Te amo."],
    category: "family",
    difficulty: 1,
    notes: "'Te quiero' = everyday warm love (family, kids). 'Te amo' = deeper romantic. With Charlotte: 'te quiero.'",
  },
  {
    id: "f11",
    english: "Come here, sweetheart.",
    spanish: "Ven acá, mi amor.",
    alternates: ["Ven aquí, mi amor.", "Ven, cariño."],
    category: "family",
    difficulty: 1,
    notes: "'Mi amor' is the most common term of endearment for kids and partners in Mexico.",
  },
  {
    id: "f12",
    english: "How was your day?",
    spanish: "¿Cómo estuvo tu día?",
    alternates: ["¿Qué tal tu día?"],
    category: "family",
    difficulty: 1,
  },
  {
    id: "f13",
    english: "Let's go to the park tomorrow.",
    spanish: "Vamos al parque mañana.",
    category: "family",
    difficulty: 1,
  },
  {
    id: "f14",
    english: "She doesn't want to eat her vegetables.",
    spanish: "No quiere comerse las verduras.",
    alternates: ["No quiere comer sus verduras."],
    category: "family",
    difficulty: 2,
  },

  // ---------- WORK / M&A / LEGAL ----------
  {
    id: "w1",
    english: "I'm a lawyer.",
    spanish: "Soy abogado.",
    category: "work",
    difficulty: 1,
    notes: "'Abogada' if female.",
  },
  {
    id: "w2",
    english: "I work in mergers and acquisitions.",
    spanish: "Trabajo en fusiones y adquisiciones.",
    category: "work",
    difficulty: 2,
  },
  {
    id: "w3",
    english: "The deal closes next month.",
    spanish: "La operación se cierra el próximo mes.",
    alternates: ["El trato se cierra el próximo mes.", "La transacción se cierra el próximo mes."],
    category: "work",
    difficulty: 2,
  },
  {
    id: "w4",
    english: "I need to review the contract before signing.",
    spanish: "Necesito revisar el contrato antes de firmar.",
    category: "work",
    difficulty: 2,
  },
  {
    id: "w5",
    english: "We're waiting for the buyer's response.",
    spanish: "Estamos esperando la respuesta del comprador.",
    category: "work",
    difficulty: 2,
  },
  {
    id: "w6",
    english: "The valuation came in lower than expected.",
    spanish: "La valuación resultó más baja de lo esperado.",
    alternates: ["La valoración fue más baja de lo esperado."],
    category: "work",
    difficulty: 3,
    notes: "In Mexico, 'valuación' is more common than 'valoración' for financial valuations.",
  },
  {
    id: "w7",
    english: "I have a meeting in twenty minutes.",
    spanish: "Tengo una junta en veinte minutos.",
    alternates: ["Tengo una reunión en veinte minutos."],
    category: "work",
    difficulty: 1,
    notes: "'Junta' is the everyday Mexican word for meeting; 'reunión' is more formal/general.",
  },
  {
    id: "w8",
    english: "Can you send me the documents by Friday?",
    spanish: "¿Me puedes mandar los documentos para el viernes?",
    alternates: ["¿Me puedes enviar los documentos para el viernes?"],
    argentine: "¿Me podés mandar los documentos para el viernes?",
    category: "work",
    difficulty: 2,
  },
  {
    id: "w9",
    english: "I'll get back to you tomorrow.",
    spanish: "Te respondo mañana.",
    alternates: ["Te contesto mañana."],
    category: "work",
    difficulty: 1,
  },
  {
    id: "w10",
    english: "We didn't reach an agreement.",
    spanish: "No llegamos a un acuerdo.",
    category: "work",
    difficulty: 2,
  },

  // ---------- BA TRAVEL (still useful for the trip — kept Mexican neutral, Argentine variants tagged) ----------
  {
    id: "ba1",
    english: "Take me to Palermo, please.",
    spanish: "Lléveme a Palermo, por favor.",
    argentine: "Lleváme a Palermo, por favor.",
    category: "ba_travel",
    difficulty: 1,
  },
  {
    id: "ba2",
    english: "How much does it cost?",
    spanish: "¿Cuánto cuesta?",
    alternates: ["¿Cuánto sale?"],
    category: "ba_travel",
    difficulty: 1,
    notes: "In Argentina, '¿Cuánto sale?' is the conversational default.",
  },
  {
    id: "ba3",
    english: "I'll have the steak, medium rare.",
    spanish: "Quiero el bistec término medio rojo.",
    alternates: ["Me da el bistec, término medio rojo."],
    argentine: "Me trae el bife, jugoso.",
    category: "ba_travel",
    difficulty: 2,
    notes: "Mexico: 'bistec, término medio rojo.' Argentina: 'bife, jugoso.' Different words, same dish.",
  },
  {
    id: "ba4",
    english: "Where is the nearest subway station?",
    spanish: "¿Dónde está la estación de metro más cercana?",
    argentine: "¿Dónde está la estación de subte más cercana?",
    category: "ba_travel",
    difficulty: 2,
    notes: "Mexico City: 'metro.' Buenos Aires: 'subte.'",
  },
  {
    id: "ba5",
    english: "I don't speak much Spanish, but I'm learning.",
    spanish: "No hablo mucho español, pero estoy aprendiendo.",
    category: "ba_travel",
    difficulty: 2,
  },
  {
    id: "ba6",
    english: "Can you speak more slowly, please?",
    spanish: "¿Puedes hablar más despacio, por favor?",
    argentine: "¿Podés hablar más despacio, por favor?",
    category: "ba_travel",
    difficulty: 1,
    notes: "Single most useful sentence for any trip. Memorize.",
  },
  {
    id: "ba7",
    english: "I'm here for my birthday.",
    spanish: "Estoy aquí por mi cumpleaños.",
    argentine: "Estoy acá por mi cumpleaños.",
    category: "ba_travel",
    difficulty: 1,
  },
  {
    id: "ba8",
    english: "What do you recommend?",
    spanish: "¿Qué me recomienda?",
    argentine: "¿Qué me recomendás?",
    category: "ba_travel",
    difficulty: 2,
  },
  {
    id: "ba9",
    english: "The check, please.",
    spanish: "La cuenta, por favor.",
    category: "ba_travel",
    difficulty: 1,
  },
  {
    id: "ba10",
    english: "I'd like a glass of red wine.",
    spanish: "Quisiera una copa de vino tinto.",
    alternates: ["Me da una copa de vino tinto, por favor."],
    category: "ba_travel",
    difficulty: 2,
  },

  // ---------- DAILY ----------
  {
    id: "d1",
    english: "I'll be there in five minutes.",
    spanish: "Llego en cinco minutos.",
    alternates: ["Voy a estar ahí en cinco minutos."],
    category: "daily",
    difficulty: 1,
  },
  {
    id: "d2",
    english: "I forgot to do it.",
    spanish: "Se me olvidó hacerlo.",
    alternates: ["Olvidé hacerlo."],
    category: "daily",
    difficulty: 2,
    notes: "'Se me olvidó' = 'it forgot itself to me' — very natural in Mexican Spanish.",
  },
  {
    id: "d3",
    english: "I'm running late.",
    spanish: "Voy tarde.",
    alternates: ["Llego tarde.", "Se me hizo tarde."],
    category: "daily",
    difficulty: 1,
    notes: "'Se me hizo tarde' is the most natural Mexican phrasing.",
  },
  {
    id: "d4",
    english: "Can you do me a favor?",
    spanish: "¿Me puedes hacer un favor?",
    argentine: "¿Me podés hacer un favor?",
    category: "daily",
    difficulty: 1,
  },
  {
    id: "d5",
    english: "I had a long day.",
    spanish: "Tuve un día largo.",
    alternates: ["Fue un día largo."],
    category: "daily",
    difficulty: 1,
  },
  {
    id: "d6",
    english: "I haven't decided yet.",
    spanish: "Todavía no he decidido.",
    alternates: ["Aún no lo he decidido.", "Todavía no decido."],
    category: "daily",
    difficulty: 2,
  },
  {
    id: "d7",
    english: "Let me think about it.",
    spanish: "Déjame pensarlo.",
    argentine: "Dejame pensarlo.",
    category: "daily",
    difficulty: 2,
  },
  {
    id: "d8",
    english: "It depends.",
    spanish: "Depende.",
    category: "daily",
    difficulty: 1,
  },
  {
    id: "d9",
    english: "I'm tired.",
    spanish: "Estoy cansado.",
    category: "daily",
    difficulty: 1,
  },
  {
    id: "d10",
    english: "What time is it?",
    spanish: "¿Qué hora es?",
    category: "daily",
    difficulty: 1,
  },
  {
    id: "d11",
    english: "I don't understand.",
    spanish: "No entiendo.",
    category: "daily",
    difficulty: 1,
  },
  {
    id: "d12",
    english: "Can you repeat that?",
    spanish: "¿Puedes repetir?",
    argentine: "¿Podés repetir?",
    category: "daily",
    difficulty: 1,
  },
  {
    id: "d13",
    english: "Sounds good.",
    spanish: "Suena bien.",
    alternates: ["Está bien.", "Va."],
    category: "daily",
    difficulty: 1,
    notes: "Mexico: 'va' is super common as a casual 'OK / sounds good.'",
  },
  {
    id: "d14",
    english: "What's up?",
    spanish: "¿Qué onda?",
    alternates: ["¿Qué tal?", "¿Cómo va todo?"],
    category: "daily",
    difficulty: 1,
    notes: "'¿Qué onda?' is peak Mexican casual greeting.",
  },

  // ---------- DEALMAKING ----------
  {
    id: "dm1",
    english: "We need to find a fair price.",
    spanish: "Necesitamos encontrar un precio justo.",
    category: "dealmaking",
    difficulty: 2,
  },
  {
    id: "dm2",
    english: "That's a deal.",
    spanish: "Trato hecho.",
    category: "dealmaking",
    difficulty: 1,
    notes: "Universal closer. Use for everything from contracts to bedtime negotiations with Charlotte.",
  },
  {
    id: "dm3",
    english: "Let me make a counteroffer.",
    spanish: "Déjame hacer una contraoferta.",
    argentine: "Dejame hacer una contraoferta.",
    category: "dealmaking",
    difficulty: 2,
  },
  {
    id: "dm4",
    english: "We can't pay more than that.",
    spanish: "No podemos pagar más que eso.",
    category: "dealmaking",
    difficulty: 2,
  },
  {
    id: "dm5",
    english: "Both parties have to agree.",
    spanish: "Ambas partes tienen que estar de acuerdo.",
    alternates: ["Las dos partes tienen que estar de acuerdo."],
    category: "dealmaking",
    difficulty: 2,
  },
  {
    id: "dm6",
    english: "I think we have an understanding.",
    spanish: "Creo que tenemos un entendimiento.",
    category: "dealmaking",
    difficulty: 3,
  },
];

export const CATEGORY_META: Record<Category, { label: string; emoji: string; color: string }> = {
  family: { label: "Family", emoji: "👨‍👩‍👧", color: "text-pink-400" },
  work: { label: "Work / M&A", emoji: "💼", color: "text-blue-400" },
  ba_travel: { label: "Travel", emoji: "✈️", color: "text-sun-arg" },
  daily: { label: "Daily", emoji: "☕", color: "text-gray-300" },
  dealmaking: { label: "Dealmaking", emoji: "🤝", color: "text-accent-green" },
};

export function getRandomPrompt(filter?: { category?: Category; difficulty?: Difficulty }): Prompt {
  let pool = PROMPTS;
  if (filter?.category) pool = pool.filter((p) => p.category === filter.category);
  if (filter?.difficulty) pool = pool.filter((p) => p.difficulty === filter.difficulty);
  if (pool.length === 0) pool = PROMPTS;
  return pool[Math.floor(Math.random() * pool.length)];
}
